loadtest:
  name: my-loadtest
  locust_locustfile_configmap: my-loadtest-locustfile
  locust_locustfile: locustfile.py
  pip_packages:
    - locust-plugins
    - python-dotenv

  mount_external_secret:
    mountPath: seed-data
    files:
      seed-data: [ seed-data.csv ]

worker:
  replicas: 6
