loadtest:
  name: my-loadtest
  locust_locustfile_configmap: my-loadtest-locustfile
  locust_locustfile: locustfile.py
  pip_packages:
    - locust-plugins
    - python-dotenv
    - beautifulsoup4

  mount_external_secret:
    mountPath: seed-data
    files: {}

worker:
  replicas: 6
